name: Container Lab CI

on: [push, pull_request]

jobs:
  clab_test_docker:
    name: CLab Test with Docker
    runs-on: ghcr.io/srl-labs/clab

    steps:

      - name: Run tests with clab (DinD)
        run: containerlab generate --name test --image srl=srlinux --nodes 8,4 --deploy

  clab_test_bash:
    name: CLab Test without Docker
    runs-on: ubuntu-latest

    steps:

      - name: install clab
        run: bash -c "$(curl -sL https://get.containerlab.dev)" -- -v 0.48.1

      - name: Run tests with clab (DinD)
        run: containerlab generate --name test --image srl=srlinux --nodes 8,4 --deploy
