name: Container Lab CI

on: [push, pull_request]

jobs:
  clab_test_docker:
    name: CLab Test with Docker
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/srl-labs/clab

    steps:

      - name: Run tests with clab (Docker)
        run: containerlab generate --name test --image srl=ghcr.io/nokia/srlinux --nodes 8,4 --deploy

  clab_test_bash:
    name: CLab Test without Docker
    runs-on: ubuntu-latest

    steps:

      - name: install clab
        run: bash -c "$(curl -sL https://get.containerlab.dev)"

      - name: Run tests with clab (DinD)
        run: sudo containerlab generate --name test --image srl=ghcr.io/nokia/srlinux --nodes 8,4 --deploy
